set(_CATKIN_CURRENT_PACKAGE "tcnav")
set(tcnav_VERSION "1.2.1")
set(tcnav_MAINTAINER "Pyo <pyo@robotis.com>")
set(tcnav_PACKAGE_FORMAT "2")
set(tcnav_BUILD_DEPENDS )
set(tcnav_BUILD_EXPORT_DEPENDS )
set(tcnav_BUILDTOOL_DEPENDS "catkin")
set(tcnav_BUILDTOOL_EXPORT_DEPENDS )
set(tcnav_EXEC_DEPENDS "amcl" "map_server" "move_base")
set(tcnav_RUN_DEPENDS "amcl" "map_server" "move_base")
set(tcnav_TEST_DEPENDS )
set(tcnav_DOC_DEPENDS )
set(tcnav_URL_WEBSITE "")
set(tcnav_URL_BUGTRACKER "")
set(tcnav_URL_REPOSITORY "")
set(tcnav_DEPRECATED "")