set(_CATKIN_CURRENT_PACKAGE "toiletcleaner")
set(toiletcleaner_VERSION "1.0.0")
set(toiletcleaner_MAINTAINER " <TODO@email.com>")
set(toiletcleaner_PACKAGE_FORMAT "2")
set(toiletcleaner_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(toiletcleaner_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(toiletcleaner_BUILDTOOL_DEPENDS "catkin")
set(toiletcleaner_BUILDTOOL_EXPORT_DEPENDS )
set(toiletcleaner_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(toiletcleaner_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(toiletcleaner_TEST_DEPENDS )
set(toiletcleaner_DOC_DEPENDS )
set(toiletcleaner_URL_WEBSITE "")
set(toiletcleaner_URL_BUGTRACKER "")
set(toiletcleaner_URL_REPOSITORY "")
set(toiletcleaner_DEPRECATED "")