# CMake generated Testfile for 
# Source directory: /home/davinio/catkin_ws/src/moveit/moveit_core/collision_detection_bullet
# Build directory: /home/davinio/catkin_ws/build_isolated/moveit_core/collision_detection_bullet
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_moveit_core_gtest_test_bullet_collision_detection "/home/davinio/catkin_ws/build_isolated/moveit_core/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/davinio/catkin_ws/build_isolated/moveit_core/test_results/moveit_core/gtest-test_bullet_collision_detection.xml" "--return-code" "/home/davinio/catkin_ws/devel_isolated/moveit_core/lib/moveit_core/test_bullet_collision_detection --gtest_output=xml:/home/davinio/catkin_ws/build_isolated/moveit_core/test_results/moveit_core/gtest-test_bullet_collision_detection.xml")
add_test(_ctest_moveit_core_gtest_test_bullet_collision_detection_panda "/home/davinio/catkin_ws/build_isolated/moveit_core/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/davinio/catkin_ws/build_isolated/moveit_core/test_results/moveit_core/gtest-test_bullet_collision_detection_panda.xml" "--return-code" "/home/davinio/catkin_ws/devel_isolated/moveit_core/lib/moveit_core/test_bullet_collision_detection_panda --gtest_output=xml:/home/davinio/catkin_ws/build_isolated/moveit_core/test_results/moveit_core/gtest-test_bullet_collision_detection_panda.xml")
add_test(_ctest_moveit_core_gtest_test_bullet_continuous_collision_checking "/home/davinio/catkin_ws/build_isolated/moveit_core/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/davinio/catkin_ws/build_isolated/moveit_core/test_results/moveit_core/gtest-test_bullet_continuous_collision_checking.xml" "--return-code" "/home/davinio/catkin_ws/devel_isolated/moveit_core/lib/moveit_core/test_bullet_continuous_collision_checking --gtest_output=xml:/home/davinio/catkin_ws/build_isolated/moveit_core/test_results/moveit_core/gtest-test_bullet_continuous_collision_checking.xml")
